#!/bin/bash
cd /code
apt-get update -qq && apt-get install -y -qq python3-pip 2>&1
pip3 install -r requirements.txt -t /code/deps 2>&1
export PYTHONPATH=/code/deps:$PYTHONPATH
python3 -m uvicorn main:app --host 0.0.0.0 --port 9000
